os:
  - linux

language: node_js

node_js:
  - 4
  - 6

before_script:
  - cp .env.travis .env

before_install:
  - npm install -g node-gyp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5